version: "3.9"
services:
  validator:
    user: root
    build:
      context: .
    container_name: validator
    volumes:
      - ./validator:/build/openethereum/worker
      - ./log:/build/openethereum/log
    restart: unless-stopped
    entrypoint: /build/openethereum/start.sh
    environment:
      #CHANGE NAT_IP to your IP
      NAT_IP: 130.183.252.7
      #If you have multiple addresses, you can specify one address for the authority node.
      #AUTH_ADDRESS: 0xab59a1ea1ac9af9f77518b9b4ad80942ade35088
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
